language : java
jdk :
  - openjdk11

branches :
  only :
    - dev

cache :
  directories:
    - '$HOME/.gradle'

script : "./gradlew clean build"  // spring에서 빌드하는 명령어

notifications:
  email:
    recipients
      - ehddn977@naver.com