name: Deploy

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with gradle
        run: |
          cd server/server
          chmod +x gradlew
          ./gradlew clean build -x test  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REPOSITORY: web-server
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./server/server
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"

      - name: Deploy to Alpha server
        uses: appleboy/ssh-action@master
        env:
          IMAGE: ${{steps.build-image.outputs.image}}
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REGION: ${{secrets.AWS_REGION}}
        with:
          host: ${{ secrets.HOST_DNS_1 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE,REGISTRY,REGION
          port: 22
          script : |
            docker login -u AWS -p $(aws ecr get-login-password --region $REGION) $REGISTRY
            docker rm -f $(docker ps -qa)
            docker rmi $(docker images -q)
            docker pull $IMAGE
            docker run -v accessLog:/tmp -p 8080:8080 -d $IMAGE

      - name: Deploy to Beta server
        uses: appleboy/ssh-action@master
        env:
          IMAGE: ${{steps.build-image.outputs.image}}
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REGION: ${{secrets.AWS_REGION}}
        with:
          host: ${{ secrets.HOST_DNS_2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE,REGISTRY,REGION
          port: 22
          script : |
            docker login -u AWS -p $(aws ecr get-login-password --region $REGION) $REGISTRY
            docker rm -f $(docker ps -qa)
            docker rmi $(docker images -q)
            docker pull $IMAGE
            docker run -p 8080:8080 -d $IMAGE
